### ISSUE TITLE
add proper licence file 

### ISSUE THREAD

**Issue by beuled** [bihealth/metaquac#2]
I think we agreed on MIT

**Comment by mkuhring** [comment]
The MIT license has been stated so far in the DESCRIPTION file as suggested by Wickham: http://r-pkgs.had.co.nz/description.html#license

But I agree that it is easier to find it in the LICENSE file if anybody is looking just for the licence and not for the general package information. So I added the MIT license according to this: https://opensource.org/licenses/MIT
