### ISSUE TITLE
Any plans to support p180

### ISSUE THREAD

**Issue by rsalek** [bihealth/metaquac#5]
Hi Mathias,

This must a common FAQ, but why p180 is not supported? The headers seem to be more or less the same? 
Best, 
Reza

**Comment by mkuhring** [comment]
Hey Reza,

In fact the headers are the same. We just have our first kit measured and I
didn't know before. I wrote a small patch, will push tomorrow.

Best, Mathias

Reza Salek <notifications@github.com> schrieb am Mi., 4. März 2020, 18:33:

**Comment by rsalek** [comment]
> I wrote a small patch, will push tomorrow.
Thanks :)

**Comment by rsalek** [comment]
> will push tomorrow. Best, Mathias  

Thanks

**Comment by mkuhring** [comment]
Update pushed.
