### ISSUE TITLE
Error for example code in metaquac v. 0.1.32.9001

### ISSUE THREAD

**Issue by madeleineernst** [bihealth/metaquac#7]
Hi Mathias,

Thanks for this nice package! I'm having some issues with running the Biocrates MxP Quant 500 Kit example code:

macOS Big Sur, Version 11.1
R version 4.0.4 (2021-02-15)
> packageVersion("metaquac")
[1] ‘0.1.32.9001’

# Biocrates MxP Quant 500 Kit - LC injection
metaquac::create_qc_report(
data_files = list(
  Batch1 = c(
    system.file("extdata", "biocrates_q500_test_01/Batch1_LC.txt", package = "metaquac"))),
kit = "Biocrates MxP Quant 500 Kit",
measurement_type = "LC",
title = "Biocrates QC - Q500 - LC",
report_output_name = "biocrates_qc_q500_lc",
report_output_dir = "biocrates_q500_test",
pool_indicator = "Sex",
profiling_variables = c('Sex'),
study_variables = list('Sex'),
replicate_variables = c('Sex')
)

**Error:**: 'stat_dens2d_filter' is not an exported object from 'namespace:ggpmisc'
**Error:** in eval(expr, envir, enclos): object 'sd_mean_comp' not found
Quitting from lines 48-89 (./nbc_qc_compound_variability.Rmd)
Quitting from lines NA-131 (./nbc_qc_compound_variability.Rmd)
Error in eval(parse_only(code), envir = envir) :
  object 'compound_var_stats' not found
In addition: Warning message:
In all(lapply(l, function(x) { :
  coercing argument of type 'list' to logical

Any idea what could be causing it? Many thanks in advance!

Best,
Madeleine

**Comment by madeleineernst** [comment]
PR #8 should fix the issue.

**Comment by mkuhring** [comment]
Thanks for the PR. Found the same solution yesterday, just wasn't able to fully test it yet. Will complete it tomorrow.

**Comment by mkuhring** [comment]
@madeleineernst Merged the fix. Hope it works now. Otherwise let me know. Thanks for reporting and investigating!

**Comment by madeleineernst** [comment]
Thanks, @mkuhring works like a charm! :)
